### ISSUE TITLE
Deploying with terraform

### ISSUE THREAD

**Issue by dennislapchenko** [bjerkio/google-cloud-logger-slack#134]
Could you guys please update your documentations as to how people can install with methods other than the 2 you are suggesting? Would help to better understand whats under the bonnet too.

**Comment by cobraz** [comment]
Hello 👋

I can see if I can create a terraform variant too :)

**Comment by simenandre** [comment]
We just recently added container images with this to promote using Cloud Run and Eventarc, this will also make it easier for Terraform users.

Following this guide will be helpful:
https://cloud.google.com/eventarc/docs/creating-triggers-terraform

**Comment by simenandre** [comment]
You can use this image from Docker Hub:
https://hub.docker.com/r/bjerkbot/google-cloud-logger-slack/tags

**Comment by simenandre** [comment]
Hello!

I've added an example here:
https://github.com/bjerkio/google-cloud-logger-slack/tree/main/examples/terraform

Would love to get your feedback on it!
